---
stages:
  - test

testing:
  image: python:3.8
  stage: test
  script:
    - pip install .[test]
    - isort -c .
    - black --check .
    - apache-license-check --copyright "2019-2020 SURF" oauth2_lib
    - flake8 --tee --output-file flake8.txt
    - flake8_junit flake8.txt report-flake8.xml
    - mypy . --junit-xml report-mypy.xml
    - pytest -vvv --cov-branch --cov-fail-under=61 --cov=oauth2_lib --cov-config=.coveragerc --junitxml=report-pytest.xml
  tags:
    - python-lint-ext
