---
stages:
  - test

lint check:
    image: python:3.7
    stage: test
    script:
      - pip install flake8 flake8-mypy --quiet
      - flake8
      - mypy -p oauth2_lib
      - pytest
    tags:
      - python-lint-ext
