---
stages:
  - test

testing:
    image: python:3.7
    stage: test
    script:
      - pip install .[test]
      - black . --check
      - isort -rc -c
      - flake8 .
      - mypy -p oauth2_lib
      - pytest
    tags:
      - python-lint-ext
